version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /data/db

  populate:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    command: ["python", "main.py", "--populate"]

volumes:
  mongo-data:
